automation:

# ------------------------------------------------
# EMS FOXESS CONTROLLER
# ------------------------------------------------

  - alias: EMS FoxESS Controller
    id: ems_foxess_controller
    mode: restart

    trigger:

      - platform: state
        entity_id:
          - sensor.ems_foxess_mode
          - input_number.foxess_ems_min_soc
          - input_number.foxess_ems_max_soc
          - input_number.foxess_ems_fd_soc
          - input_number.foxess_ems_fd_power
          - sensor.ems_energy_strategy

    condition:

      - condition: template
        value_template: >

          {% set enable = 1 %}
          {% set start_time = (0 * 256) + 0 %}
          {% set end_time = (23 * 256) + 59 %}
          {% set work_mode = states('sensor.ems_foxess_mode') | int(1) %}
          {% set min_soc = states('input_number.foxess_ems_min_soc') | int(20) %}
          {% set max_soc = states('input_number.foxess_ems_max_soc') | int(95) %}
          {% set fd_soc = states('input_number.foxess_ems_fd_soc') | int(20) %}
          {% set fd_power = states('input_number.foxess_ems_fd_power') | int(4000) if states('sensor.ems_energy_strategy') in ['discharge','export'] else 0 %}

          {% set packed_soc = (max_soc * 256) + min_soc %}

          {% set signature = enable ~ '-' ~ start_time ~ '-' ~ end_time ~ '-' ~ work_mode ~ '-' ~ packed_soc ~ '-' ~ fd_soc ~ '-' ~ fd_power %}

          {{ signature != states('input_text.foxess_last_signature') }}

    action:

# ------------------------------------------------
# WRITE MODBUS BLOCK
# ------------------------------------------------

      - service: modbus.write_register
        data:

          hub: foxess_modbus
          slave: 247
          address: 48010

          value:

            - 1
            - "{{ (0 * 256) + 0 }}"
            - "{{ (23 * 256) + 59 }}"
            - "{{ states('sensor.ems_foxess_mode') | int(1) }}"
            - "{{ (states('input_number.foxess_ems_max_soc') | int(95) * 256) + states('input_number.foxess_ems_min_soc') | int(20) }}"
            - "{{ states('input_number.foxess_ems_fd_soc') | int(20) }}"
            - "{{ states('input_number.foxess_ems_fd_power') | int(4000) if states('sensor.ems_energy_strategy') in ['discharge','export'] else 0 }}"
            - 0
            - 0
            - 0

# ------------------------------------------------
# SAVE SIGNATURE
# ------------------------------------------------

      - service: input_text.set_value
        data:

          entity_id: input_text.foxess_last_signature

          value: >

            {% set enable = 1 %}
            {% set start_time = (0 * 256) + 0 %}
            {% set end_time = (23 * 256) + 59 %}
            {% set work_mode = states('sensor.ems_foxess_mode') | int(1) %}
            {% set min_soc = states('input_number.foxess_ems_min_soc') | int(20) %}
            {% set max_soc = states('input_number.foxess_ems_max_soc') | int(95) %}
            {% set fd_soc = states('input_number.foxess_ems_fd_soc') | int(20) %}
            {% set fd_power = states('input_number.foxess_ems_fd_power') | int(4000) if states('sensor.ems_energy_strategy') in ['discharge','export'] else 0 %}
            {% set packed_soc = (max_soc * 256) + min_soc %}
            {{ enable ~ '-' ~ start_time ~ '-' ~ end_time ~ '-' ~ work_mode ~ '-' ~ packed_soc ~ '-' ~ fd_soc ~ '-' ~ fd_power }}
